
version: 2

sources:
  - name: globepay
    description: A replica of Globepay PSP API data.
    tables:
      - name: acceptance_report
        description: The transactions processed by Globepay. 
      - name: chargeback_report
        description: Information on whether a Globepay transaction incurred a charge back. 

models:
  - name: stg_chargebacks
    description: "Chargebacks from Globepay API"
    columns:
      - name: chargeback_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: chargeback_status
      - name: chargeback_source
      - name: is_chargeback

  - name: stg_transactions
    description: "Transactions from Globepay API"
    columns:
      - name: transaction_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: chargeback_id
      - name: transaction_country
      - name: transaction_currency
      - name: exchange_rates
      - name: transaction_status
      - name: transaction_source
      - name: transaction_state
      - name: transaction_amount
      - name: is_cvv_provided
      - name: transaction_date
