
version: 2

sources:
  - name: global_pay
    description: A replica of Global Pay PSP API data.
    tables:
      - name: acceptance_report
        description: The transactions processed by Global Pay. 
      - name: chargeback_report
        description: Information on whether a Global Pay transaction incurred a charge back. 

models:
  - name: stg_chargebacks
    description: "Chargebacks from Globalpay API"
    columns:
      - name: chargeback_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: chargeback_status
      - name: chargeback_source
      - name: is_chargeback

  - name: stg_transactions
    description: "Transactions from Globalpay API"
    columns:
      - name: transaction_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: chargeback_id
      - name: transaction_country
      - name: transaction_currency
      - name: exchange_rates
      - name: transaction_status
      - name: transaction_source
      - name: transaction_state
      - name: transaction_amount
      - name: is_cvv_provided
      - name: transaction_date
